### ISSUE TITLE
links to ttt rules

### ISSUE THREAD

**Issue by WarpedMetal** [riley805/TTT-Issue-Tracker#59]
the links that lead to the ttt rules probably need to be updated since we're moving to a new domain. Currently, the motd, !rules, and the forums page of rules (https://forums.playbtg.com/threads/moved-full-list-of-ttt-rules.12/) all lead to say the rules were moved to playbtg.com/rules. This is a slightly incorrect url that is being linked, as the list of rules is actually located at playbtg.com/ttt-rules

**Comment by riley805** [comment]
The links will be updated when the forums shut down. From now until the end of the month the forums are still the primary communication method and links will point to it.
